language: csharp
mono: none
dotnet: 2.1
script:
   -  dotnet build FileService.Api.Web.csproj
   -  dotnet test FileService.Api.DataAccess.csproj
   -  dotnet test FileService.Api.Servicea.csproj
   -  dotnet test FileService.Api.Client.csproj
   -  dotnet test FileService.Api.Web.csproj